In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
x = df.iloc[:,3:13]
y = df['Exited']

In [5]:
x.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [6]:
x.shape, y.shape

((10000, 10), (10000,))

In [7]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
dtypes: float64(2), int64(6), object(2)
memory usage: 781.4+ KB


In [8]:
x.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
dtype: int64

In [9]:
x.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [13]:
# df.Geography = [ i for i in df.Geography.replace({'France':0, 'Spain':1, 'Germany':2})]

In [11]:
df.Gender.unique()

array(['Female', 'Male'], dtype=object)

In [14]:
# df.Gender = [ i for i in df.Gender.replace({'Male':0, 'Female':1})]

In [15]:
# convert categorical data into numerical data..

from sklearn.preprocessing import LabelEncoder              

In [16]:
label_1 = LabelEncoder()

x['Geography'] = label_1.fit_transform(x['Geography'])

In [17]:
label_2 = LabelEncoder()

x['Gender'] = label_2.fit_transform(x['Gender'])

In [19]:
x.head(15)

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0           619          0       0  ...          1               1        101348.88
1           608          2       0  ...          0               1        112542.58
2           502          0       0  ...          1               0        113931.57
3           699          0       0  ...          0               0         93826.63
4           850          2       0  ...          1               1         79084.10
5           645          2       1  ...          1               0        149756.71
6           822          0       1  ...          1               1         10062.80
7           376          1       0  ...          1               0        119346.88
8           501          0       1  ...          0               1         74940.50
9           684          0       1  ...          1               1         71725.73
10          528          0       1  ...          0               0         80181.12
11          497          2       1  ...          1               0         76390.01
12          476          0       0  ...          1               0         26260.98
13          549          0       0  ...          0               0        190857.79
14          635          2       0  ...          1               1         65951.65

[15 rows x 10 columns]

In [21]:
# avoid dummy variable trap...

x = pd.get_dummies(data=x, drop_first=True, columns=['Geography'])

In [23]:
x.head(15)

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0           619       0   42  ...        101348.88            0            0
1           608       0   41  ...        112542.58            0            1
2           502       0   42  ...        113931.57            0            0
3           699       0   39  ...         93826.63            0            0
4           850       0   43  ...         79084.10            0            1
5           645       1   44  ...        149756.71            0            1
6           822       1   50  ...         10062.80            0            0
7           376       0   29  ...        119346.88            1            0
8           501       1   44  ...         74940.50            0            0
9           684       1   27  ...         71725.73            0            0
10          528       1   31  ...         80181.12            0            0
11          497       1   24  ...         76390.01            0            1
12          476       0   34  ...         26260.98            0            0
13          549       0   25  ...        190857.79            0            0
14          635       0   35  ...         65951.65            0            1

[15 rows x 11 columns]

In [25]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [30]:
x_train

array([[ 0.16958176, -1.09168714, -0.46460796, ...,  1.10643166,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.91601335,  0.30102557, ..., -0.74866447,
         1.75486502, -0.57369368],
       [-1.19119591, -1.09168714, -0.94312892, ...,  1.48533467,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 ,  0.91601335, -0.36890377, ...,  1.41231994,
        -0.5698444 , -0.57369368],
       [-0.62420521, -1.09168714, -0.08179119, ...,  0.84432121,
        -0.5698444 ,  1.74309049],
       [-0.28401079, -1.09168714,  0.87525072, ...,  0.32472465,
         1.75486502, -0.57369368]])

In [31]:
x_test

array([[-0.55204276, -1.09168714, -0.36890377, ...,  1.61085707,
         1.75486502, -0.57369368],
       [-1.31490297, -1.09168714,  0.10961719, ...,  0.49587037,
        -0.5698444 , -0.57369368],
       [ 0.57162971, -1.09168714,  0.30102557, ..., -0.42478674,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227,  0.91601335, -0.27319958, ...,  0.71888467,
        -0.5698444 ,  1.74309049],
       [-0.00566991,  0.91601335, -0.46460796, ..., -1.54507805,
         1.75486502, -0.57369368],
       [-0.79945688,  0.91601335, -0.84742473, ...,  1.61255917,
         1.75486502, -0.57369368]])

In [32]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [33]:
model = Sequential()

model.add(Dense(units=6, activation='relu',input_dim=11))        # input layer
model.add(Dense(units=6, activation='relu'))           # 1st hidden layer
model.add(Dense(units=1, activation='sigmoid'))        # uotput layer

In [34]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 72        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [40]:
model.fit(x_train,y_train,epochs=20,batch_size=12)

Epoch 1/20
667/667 [==============================] - 2s 2ms/step - loss: 0.3381 - accuracy: 0.8627
Epoch 2/20
667/667 [==============================] - 1s 2ms/step - loss: 0.3383 - accuracy: 0.8629
Epoch 3/20
667/667 [==============================] - 1s 2ms/step - loss: 0.3379 - accuracy: 0.8620
Epoch 4/20
667/667 [==============================] - 1s 2ms/step - loss: 0.3385 - accuracy: 0.8615
Epoch 5/20
667/667 [==============================] - 1s 2ms/step - loss: 0.3382 - accuracy: 0.8635
Epoch 6/20
667/667 [==============================] - 1s 2ms/step - loss: 0.3381 - accuracy: 0.8622
Epoch 7/20
667/667 [==============================] - 1s 2ms/step - loss: 0.3378 - accuracy: 0.8644
Epoch 8/20
667/667 [==============================] - 1s 2ms/step - loss: 0.3372 - accuracy: 0.8645
Epoch 9/20
667/667 [==============================] - 1s 2ms/step - loss: 0.3378 - accuracy: 0.8637
Epoch 10/20
667/667 [==============================] - 1s 2ms/step - loss: 0.3377 - accuracy: 0.8630

In [41]:
loss, accuracy = model.evaluate(x_test,y_test)                  # this accuracy is on test data...

63/63 [==============================] - 0s 1ms/step - loss: 0.3394 - accuracy: 0.8615


In [42]:
y_pred = model.predict(x_test)

In [52]:
from keras.metrics import binary_accuracy,accuracy

binary_accuracy(y_test,y_pred)

<tf.Tensor: shape=(2000,), dtype=float32, numpy=array([0.7975, 0.7975, 0.7975, ..., 0.7975, 0.7975, 0.7975], dtype=float32)>